uploads = []
generated = []

[[outputs]]
id = "4PJpkfubrKsqc8QXvt3NT"
uri = "file://integrity-forge.tar.gz"
type = "unspecified"
title = "IntegrityForge Source Code"

[[outputs]]
id = "d1lUuDRzvdmAgA2cVIZVx"
uri = "file://integrity-forge-src.tar.gz"
type = "unspecified"
title = "IntegrityForge Source Code"
